# Generated by Django 3.2.10 on 2021-12-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benutzer',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'benutzer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bewertung',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('textnachricht', models.CharField(max_length=2000)),
                ('erstellungsdatum', models.DateTimeField()),
                ('rating', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'bewertung',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fahrerlaubnis',
            fields=[
                ('nummer', models.SmallAutoField(primary_key=True, serialize=False)),
                ('ablaufdatum', models.DateTimeField()),
            ],
            options={
                'db_table': 'fahrerlaubnis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fahrt',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('startort', models.CharField(max_length=100)),
                ('zielort', models.CharField(max_length=100)),
                ('fahrtdatumzeit', models.DateTimeField()),
                ('maxplaetze', models.SmallIntegerField()),
                ('fahrtkosten', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=11)),
                ('beschreibung', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'fahrt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservieren',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('anzplaetze', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'reservieren',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transportmittel',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('icon', models.TextField()),
            ],
            options={
                'db_table': 'transportmittel',
                'managed': False,
            },
        ),
    ]
